import {background,daily,dimensions,score,overdue,safetyPositive,monthly,monthlyDimensions,monthlyScore,monthlyDue} from './model.js';
const key='bluejay-v1';
let state={onboarded:false,entries:[],monthlyReviews:[],remember:false}, page='Overview', range=30;
try { const saved=JSON.parse(localStorage.getItem(key)); const validEntries=Array.isArray(saved?.entries)&&saved.entries.every(e=>Number.isFinite(Date.parse(e.date))&&score(e.values)>=0); const reviews=Array.isArray(saved?.monthlyReviews)?saved.monthlyReviews:[]; const validReviews=reviews.every(r=>Number.isFinite(Date.parse(r.date))&&monthlyScore(r.values)>=0); if(saved?.onboarded&&validEntries&&validReviews) state={...state,...saved,monthlyReviews:reviews,remember:true}; } catch {}
const app=document.querySelector('#app'), dialog=document.querySelector('#dialog');
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const changeText=n=>n===0?'No change':`${n>0?'+':''}${n} points`;
function reviewChanges(current,reference){return current.map((value,index)=>({label:monthlyDimensions[index],change:value-reference[index]})).filter(item=>item.change!==0).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,3);}
function monthlyInsight(currentValues){const reviews=state.monthlyReviews, current=monthlyScore(currentValues), baseline=reviews[0], previous=reviews.at(-1), reference=previous||baseline;const baselineChange=baseline?current-monthlyScore(baseline.values):null, previousChange=previous?current-monthlyScore(previous.values):null;const changed=reference?reviewChanges(currentValues,reference.values):[];return {current,baseline,previous,baselineChange,previousChange,changed};}
function persist(){try {if(state.remember)localStorage.setItem(key,JSON.stringify(state));else localStorage.removeItem(key);}catch{alert('Your browser could not save your data. This session still works, but changes may be lost when you close it.');}}
const links=`<a href="https://wellbeing.jhu.edu/MentalHealthServices/" target="_blank" rel="noopener">JHU Mental Health Services <span>↗</span></a><a href="tel:4105169355">JHU crisis support · 410-516-9355 <span>↗</span></a><a href="tel:988">Call 988 · Suicide & Crisis Lifeline <span>↗</span></a>`;
function render(){
 const last=state.entries.at(-1), previous=state.entries.at(-2), value=last?score(last.values):null, latestReview=state.monthlyReviews.at(-1), reviewValue=latestReview?monthlyScore(latestReview.values):null, baselineReview=state.monthlyReviews[0], reviewBaselineChange=latestReview&&baselineReview?reviewValue-monthlyScore(baselineReview.values):null;
 app.innerHTML=`<aside class="sidebar"><a class="brand" href="/">b<span>✦</span> <strong>bluejay<span>YOUR SPACE TO GROW</span></strong></a><div class="campus">◈ &nbsp; JOHNS HOPKINS UNIVERSITY</div><nav>${['Overview','My check-ins','Resources','Settings'].map((n,i)=>`<button data-page="${n}" class="${page===n?'active':''}"><span>${['▦','♡','☼','⚙'][i]}</span>${n}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="little-flower">✳</div><h3>You belong here.</h3><p>Even on the days it<br>doesn’t feel like it.</p><button class="text-button" data-action="support">Find someone to talk to ↗</button></div><div class="private">♧ &nbsp; A private space, just for you</div></aside>
 <main><header><span>Your first year. Your own pace.</span><button class="support-pill" data-action="support">♡ &nbsp; Get support</button></header><div class="content"><div class="eyebrow">A LITTLE SPACE FOR YOU</div><div class="heading"><div><h1>${page==='Overview'?'Let’s check in with you.':page==='My check-ins'?'Your journey, day by day.':page==='Resources'?'You don’t have to do it alone.':'Make this space yours.'}</h1><p>${page==='Overview'?'College is a lot of firsts. Taking care of yourself can be one of them.':page==='My check-ins'?'Small moments of reflection add up. Every check-in belongs here.':page==='Resources'?'A few places to start, whenever you’re ready.':'You decide what stays on this device.'}</p></div><span class="date-tag">${new Date().toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}</span></div>
 ${page==='Overview'?`<section class="hero"><div><div class="eyebrow">PAUSE. BREATHE. BEGIN AGAIN.</div><h2>A small check-in.<br>A little more clarity.</h2><p>No perfect answers. Just a moment to notice how<br class="desktop"> you’re doing, and what you might need.</p><button class="primary" data-action="check">${state.onboarded?'Start a check-in':'Get to know yourself'} <span>↗</span></button><small>${state.onboarded?'5 questions · About 1 minute':'15 background questions + your first check-in'}</small></div><div class="plant" aria-hidden="true"><div class="sun"></div><div class="stem"></div><i class="leaf l1"></i><i class="leaf l2"></i><i class="leaf l3"></i><i class="leaf l4"></i><i class="leaf l5"></i><div class="pot"></div><span class="spark s1">✧</span><span class="spark s2">✧</span><span class="plant-note">a little growth, every day</span></div></section>
 <div class="section-title"><h2>Your wellbeing at a glance</h2><span>Your pace. Your progress.</span></div><div class="summary-grid"><section class="card score-card"><div class="card-label">WELLNESS INDEX <span>◌</span></div><div class="score">${value??'—'}<span>/ 100</span></div><span class="badge">${value===null?'Your starting point awaits':previous?`${value-score(previous.values)>=0?'+':''}${value-score(previous.values)} since your last check-in`:'Your first moment of reflection'}</span><p>A personal reflection, not a clinical assessment.</p></section><section class="card"><div class="card-label">CHECK-INS <span>♡</span></div><div class="score">${state.entries.length}<span>moments for you</span></div><p>${last?`Last check-in: ${date(last.date)}`:'A fresh start. No streaks to keep.'}</p><button class="text-button" data-page="My check-ins">See your reflections →</button></section><section class="card reminder"><div class="card-label">A GENTLE REMINDER <span>☼</span></div><h3>${overdue(state.entries)?'Make a little room for you.':'One step at a time is enough.'}</h3><p>${overdue(state.entries)?'Try to check in at least once a week. You can always come back sooner.':'Your weekly check-in is up to date. Come back whenever it feels helpful.'}</p><button class="text-button" data-action="calendar">Add a weekly reminder ↗</button></section></div>
 <section class="card monthly-review"><div><div class="eyebrow">MONTHLY WELLBEING REVIEW</div><h2>Zoom out and notice your month.</h2><p>A deeper 12-question reflection on your emotional wellbeing, classwork, connection, rest, food and hydration, and support. It compares this month with your first review and earlier reviews.</p></div><div class="monthly-review-action">${reviewValue===null?'<strong>Your baseline is waiting.</strong>':`<strong>${reviewValue}<small> / 100</small></strong><span>${reviewBaselineChange===0?'Same as your baseline':`${reviewBaselineChange>0?'+':''}${reviewBaselineChange} points from your baseline`}</span><small>Last review: ${date(latestReview.date)}</small>`}<button class="primary" data-action="monthly">${monthlyDue(state.monthlyReviews)?'Start monthly review':'Review again'} <span>↗</span></button></div></section>
 <div class="lower-grid"><section class="card trend"><div class="section-title"><h2>Your ups, downs & in-betweens</h2><select id="range" aria-label="Trend date range"><option value="7" ${range===7?'selected':''}>Last 7 days</option><option value="30" ${range===30?'selected':''}>Last 30 days</option><option value="365" ${range===365?'selected':''}>Last year</option></select></div>${chart()}<p class="muted">Progress isn’t always a straight line. That’s okay.</p></section><section class="card next"><div class="eyebrow">A SMALL NEXT STEP</div><div class="next-icon">✳</div><h3>${recommendation(last)[0]}</h3><p>${recommendation(last)[1]}</p><button class="text-button" data-page="Resources">Explore support resources ↗</button></section></div>`:''}
 ${page==='My check-ins'?`<button class="primary" data-action="check">Start a check-in ↗</button><section class="card history">${state.entries.length?state.entries.slice().reverse().map(e=>`<article><div><h3>${escape(new Date(e.date).toLocaleString())}</h3><p>${e.values.map((v,i)=>`${dimensions[i]}: ${v+1}/5`).join(' · ')}</p>${e.note?`<p>${escape(e.note)}</p>`:''}</div><strong>${score(e.values)}<small> / 100</small></strong></article>`).join(''):'<h3>Your story starts here.</h3><p>Complete your first check-in to see your history. There’s no limit to how often you can reflect.</p>'}</section><p class="muted">Index = sum of five answers (0–4 each) ÷ 20 × 100. Higher means more self-reported wellbeing. It is not a validated mental health score.</p>`:''}
 ${page==='Resources'?`<div class="resource-grid"><section class="card"><div class="eyebrow">PEOPLE WHO CAN HELP</div><h2>A conversation is a place to start.</h2><p>Connect with campus mental health services for support with stress, transitions, or ongoing concerns.</p><div class="resource-links">${links}</div></section><section class="card"><div class="eyebrow">RIGHT HERE, RIGHT NOW</div><h2>Need urgent support?</h2><p>If you might act on thoughts of suicide or self-harm, call 988 or JHU crisis support now. If you are in immediate danger, call 911 or go to the nearest emergency department. Stay with someone you trust if possible.</p><button class="primary" data-action="support">Open support options ↗</button></section></div><section class="card history"><h3>A first-year note</h3><p>For classwork, consider talking with an academic advisor about workload. For connection, try a low-pressure meal with a classmate or one club meeting. If meeting food needs is difficult, contact student support about available assistance. You can seek professional support at any index value.</p></section>`:''}
 ${page==='Settings'?`<section class="card settings"><h2>Your privacy, your choice.</h2><p>This independent student prototype is not affiliated with Johns Hopkins. No account, analytics, or server-side response storage. Saved data is unencrypted in this browser and visible to other people using this browser profile.</p><label class="toggle"><input type="checkbox" id="remember" ${state.remember?'checked':''}> Save my check-ins on this device</label><p>Leave this off for a temporary session. Background and safety responses are not saved. Closing or refreshing ends an unsaved session.</p><button class="secondary" data-action="export">Export check-in history</button><button class="danger" data-action="delete">Delete all my data</button><hr><h3>Weekly reminders</h3><p>The app shows a reminder when you return after seven days. Add a recurring calendar reminder for notifications when the app is closed. Calendar alerts depend on your calendar settings.</p><button class="secondary" data-action="calendar">Download weekly calendar reminder</button></section>`:''}
 <footer><span>Made for the firsts, and everything in between.</span><span>Self-reflection, not diagnosis. <button class="text-button" data-action="method">About your index ↗</button></span></footer></div></main>`;
 app.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render();});
 app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
 document.querySelector('#range')?.addEventListener('change',e=>{range=Number(e.target.value);render();});
 document.querySelector('#remember')?.addEventListener('change',e=>{state.remember=e.target.checked;persist();});
}
function recommendation(last){if(!last)return ['Start by noticing.','Your first check-in will help you find a small, personal next step.'];const i=last.values.indexOf(Math.min(...last.values));if(Math.min(...last.values)>=3)return ['Keep what’s helping.','Notice one routine or connection that supported you today and make a little space for it again.'];return [['Let someone in.','Consider talking with someone you trust or a campus counselor about how you’re feeling.'],['Make the workload smaller.','Choose one manageable next task. An academic advisor can help you think through classes and commitments.'],['A little connection counts.','Consider a message to a friend, a shared meal, or a low-pressure campus activity.'],['Make room for rest.','Consider a consistent wind-down time. If sleep difficulties persist, a healthcare professional can help.'],['Your basic needs matter.','Make space for food and water. If access is difficult, reach out to student support for help.']][i];}
function chart(){const entries=state.entries.filter(e=>Date.now()-new Date(e.date).getTime()<=range*86400000);if(!entries.length)return '<div class="empty-chart"><span>⌁</span><h3>A little perspective, over time.</h3><p>Your check-ins will draw the picture. Start with one.</p><div class="empty-line"></div></div>';const points=entries.map((e,i)=>`${40+(entries.length===1?250:i/(entries.length-1)*500)},${160-score(e.values)*1.3}`);return `<svg class="chart" viewBox="0 0 590 195" role="img" aria-label="Wellness index over ${entries.length} check-ins. Latest score ${score(entries.at(-1).values)} out of 100."><g stroke="#e8ece7"><path d="M40 30H560M40 95H560M40 160H560"/></g><g fill="#6d7b75" font-size="12"><text x="5" y="35">100</text><text x="12" y="100">50</text><text x="18" y="165">0</text><text x="40" y="190">${date(entries[0].date)}</text><text x="510" y="190">${date(entries.at(-1).date)}</text></g><polyline fill="none" stroke="#54785d" stroke-width="3" points="${points.join(' ')}"/>${points.map(p=>`<circle cx="${p.split(',')[0]}" cy="${p.split(',')[1]}" r="4" fill="#54785d"/>`).join('')}</svg>`;}
function modal(html){dialog.innerHTML=`<button class="close" aria-label="Close dialog">×</button>${html}`;dialog.querySelector('.close').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();}
function download(name,content,type){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function action(type){if(type==='check')start();if(type==='monthly')startMonthly();if(type==='support')support();if(type==='calendar'){const day=new Date(Date.now()+7*86400000).toISOString().slice(0,10).replaceAll('-','');download('a-moment-for-you.ics',`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Bluejay//Check-in//EN\r\nBEGIN:VEVENT\r\nUID:${crypto.randomUUID()}@bluejay.local\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}\r\nDTSTART;VALUE=DATE:${day}\r\nRRULE:FREQ=WEEKLY\r\nSUMMARY:A moment for yourself\r\nBEGIN:VALARM\r\nTRIGGER:-PT0M\r\nACTION:DISPLAY\r\nDESCRIPTION:A moment for yourself\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`,'text/calendar');}if(type==='export')download('bluejay-check-ins.json',JSON.stringify({exported:new Date().toISOString(),entries:state.entries,monthlyReviews:state.monthlyReviews},null,2),'application/json');if(type==='delete'){modal('<h2>Delete your data?</h2><p>This removes all check-ins and monthly reviews from this app and browser. Previously exported files are unaffected.</p><button class="danger" id="confirm-delete">Delete all data</button>');document.querySelector('#confirm-delete').onclick=()=>{state={onboarded:false,entries:[],monthlyReviews:[],remember:false};persist();dialog.close();render();};}if(type==='method')modal('<div class="eyebrow">A REFLECTION, NOT A LABEL</div><h2>About your wellness index</h2><p>Five check-in answers each receive 0–4 points, from less to more self-reported wellbeing. Their sum is divided by 20 and multiplied by 100. The same five questions are used each time.</p><p>The monthly review uses the same 0–4 response range across 12 current wellbeing areas. Neither index is clinically validated, and neither can diagnose a condition or determine suicide risk. Background, diagnoses, and safety responses never affect either index.</p>');}
function support(back){modal(`<div class="eyebrow">YOU DESERVE SUPPORT</div><h2>You don’t have to handle this alone.</h2><p>If you might act on thoughts of suicide or self-harm, connect with live support now. In immediate danger, call <a href="tel:911">911</a> or go to the nearest emergency department. If possible, stay with someone you trust and move away from things you could use to hurt yourself.</p><div class="resource-links">${links}</div><p>This app is not monitored and cannot contact emergency services for you.</p>${back?'<button class="secondary" id="back-flow">Return to questions</button>':''}`);if(back)document.querySelector('#back-flow').onclick=back;}
function start(){let stage=state.onboarded?'daily':'intro', index=0, answers=[], values=[], safetyDone=false;
 function show(){if(stage==='intro'){modal('<div class="eyebrow">BEFORE WE BEGIN</div><h2>A space to be honest with yourself.</h2><p>We’ll ask 15 background questions, then five questions about today. Background answers help add context to your suggestions during this session, but are never stored or scored.</p><p>This is a student prototype for self-reflection, not healthcare or a monitored service. You can close this at any time.</p><label class="toggle"><input id="consent-save" type="checkbox"> Save check-ins in this browser (optional)</label><p class="muted">Saved check-ins are unencrypted. Avoid saving on shared devices.</p><button class="primary" id="begin">Let’s begin →</button>');document.querySelector('#begin').onclick=()=>{state.remember=document.querySelector('#consent-save').checked;stage='background';show();};return;}
 const list=stage==='background'?background:daily, q=list[index];modal(`<div class="eyebrow">${stage==='background'?'GETTING TO KNOW YOU':'TODAY, IN YOUR OWN WORDS'} · ${index+1} OF ${list.length}</div><progress value="${index+1}" max="${list.length}"></progress><h2>${q[0]}</h2><form id="question"><fieldset><legend class="sr-only">Choose one answer</legend>${q[1].map((o,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" required ${((stage==='background'?answers:values)[index]===i)?'checked':''}>${o}</label>`).join('')}</fieldset>${stage==='background'&&index===1?'<label class="note-label">Optional: conditions you feel comfortable sharing<input id="conditions" maxlength="200" placeholder="You can leave this blank"></label>':''}<div class="form-actions">${index?'<button type="button" class="secondary" id="prev">← Back</button>':'<span></span>'}<button class="primary" type="submit">${index===list.length-1?'Continue':'Next'} →</button></div></form><button class="text-button" id="need-help">I need support now</button>`);
 document.querySelector('#need-help').onclick=()=>support(show);document.querySelector('#prev')?.addEventListener('click',()=>{index--;show();});
 document.querySelector('#question').onsubmit=e=>{e.preventDefault();const v=Number(new FormData(e.target).get('answer'));(stage==='background'?answers:values)[index]=v;
 const advance=()=>{if(index<list.length-1){index++;show();}else if(stage==='background'){stage='daily';index=0;show();}else finish();};
 if(stage==='background'&&index===2&&(v===2||v===3)&&!safetyDone){safetyDone=true;safety(advance,v===3);}else advance();};
 }
 function finish(){const context=answers[7]>=3?'You mentioned a heavy academic workload. An advisor or counselor may help you explore support.':answers[12]===3?'You mentioned significant demands outside class. Consider discussing practical support with someone you trust.':'';modal(`<div class="eyebrow">A MOMENT WELL SPENT</div><h2>Thank you for checking in.</h2><p>${recommendation({values})[1]}</p>${context?`<p>${context}</p>`:''}<label class="note-label">Anything you’d like to remember? (optional)<textarea id="note" rows="3" maxlength="1000" placeholder="One small thing on your mind…"></textarea></label><p class="muted">${state.remember?'This check-in will be saved on this device.':'This check-in stays only for this browser session.'}</p><button class="primary" id="save">Save my check-in →</button>`);document.querySelector('#save').onclick=()=>{state.entries.push({date:new Date().toISOString(),values:[...values],note:document.querySelector('#note').value});state.onboarded=true;persist();dialog.close();page='Overview';render();};}
 show();
}
function startMonthly(){let index=0,values=[];
 function show(){const q=monthly[index];modal(`<div class="eyebrow">MONTHLY WELLBEING REVIEW · ${index+1} OF ${monthly.length}</div><progress value="${index+1}" max="${monthly.length}"></progress><h2>${q[0]}</h2><p>This wider reflection helps you compare how this month feels with your baseline and earlier monthly reviews.</p><form id="monthly-question"><fieldset><legend class="sr-only">Choose one answer</legend>${q[1].map((option,i)=>`<label class="option"><input type="radio" name="answer" value="${i}" required ${values[index]===i?'checked':''}>${option}</label>`).join('')}</fieldset><div class="form-actions">${index?'<button type="button" class="secondary" id="monthly-prev">← Back</button>':'<span></span>'}<button class="primary" type="submit">${index===monthly.length-1?'See monthly reflection':'Next'} →</button></div></form><button class="text-button" id="monthly-support">I need support now</button>`);document.querySelector('#monthly-support').onclick=()=>support(show);document.querySelector('#monthly-prev')?.addEventListener('click',()=>{index--;show();});document.querySelector('#monthly-question').onsubmit=e=>{e.preventDefault();values[index]=Number(new FormData(e.target).get('answer'));if(index<monthly.length-1){index++;show();}else finish();};}
 function finish(){const insight=monthlyInsight(values), reference=insight.previous||insight.baseline, referenceLabel=insight.previous?'your last monthly review':'your baseline';const comparison=!insight.baseline?'<p>This is your <strong>monthly baseline</strong>. Your next monthly review will show how your wellbeing has shifted over time.</p>':`<div class="monthly-scores"><div><span>THIS MONTH</span><strong>${insight.current}<small> / 100</small></strong></div><div><span>FROM BASELINE</span><strong class="${insight.baselineChange>=0?'up':'down'}">${changeText(insight.baselineChange)}</strong></div>${state.monthlyReviews.length>1?`<div><span>FROM LAST REVIEW</span><strong class="${insight.previousChange>=0?'up':'down'}">${changeText(insight.previousChange)}</strong></div>`:''}</div><p>Compared with ${referenceLabel} from ${date(reference.date)}, your monthly reflection changed by ${changeText(insight.current-monthlyScore(reference.values))}.</p>`;const changed=insight.changed.length?`<div class="change-list"><h3>Areas that shifted most</h3>${insight.changed.map(item=>`<div><span>${item.label}</span><strong class="${item.change>0?'up':'down'}">${item.change>0?'+':''}${item.change} · ${item.change>0?'more supported':'less supported'}</strong></div>`).join('')}</div>`:'<p class="muted">No area changed from your comparison review.</p>';modal(`<div class="eyebrow">YOUR MONTHLY REFLECTION</div><h2>Here’s what you noticed this month.</h2>${comparison}${changed}<p class="muted">This is a personal reflection, not a diagnosis. The score compares your own responses over time; it does not determine whether you are safe or need care.</p><p class="muted">${state.remember?'This monthly review will be saved on this device.':'This monthly review stays only for this browser session.'}</p><button class="primary" id="save-monthly">Save monthly review →</button>`);document.querySelector('#save-monthly').onclick=()=>{state.monthlyReviews.push({date:new Date().toISOString(),values:[...values]});persist();dialog.close();page='Overview';render();};}
 show();
}
function safety(done,current){
 const questions=['In the past few weeks, have you wished you were dead?','In the past few weeks, have you felt that you or your family would be better off if you were dead?','In the past week, have you been having thoughts about killing yourself?','Have you ever tried to kill yourself?'];
 modal(`<div class="eyebrow">LET’S PAUSE FOR YOUR SAFETY</div><h2>Support comes first.</h2><p>${current?'You reported current thoughts. Please connect with live support now; you do not need to finish these questions.':'You reported recent thoughts. Please connect with a trained professional for support.'} If you are in immediate danger, call <a href="tel:911">911</a>.</p><div class="resource-links">${links}</div><p>The questions below are from the <a href="https://www.nimh.nih.gov/research/research-conducted-at-nimh/asq-toolkit-materials" target="_blank" rel="noopener">NIMH ASQ screening tool</a>, validated in medical settings. This self-guided implementation is not clinically validated and does not replace a clinician’s safety assessment. Answers are not stored or scored.</p><form id="safety">${questions.map((q,i)=>`<fieldset class="safety-question"><legend>${q}</legend>${['Yes','No','Prefer not to answer'].map(a=>`<label><input required type="radio" name="s${i}" value="${a}">${a}</label>`).join('')}${i===3?'<label class="note-label">If yes, when was the most recent attempt? (optional)<input name="timing" maxlength="100"></label>':''}</fieldset>`).join('')}<button class="primary">Continue to support →</button></form>`);
 document.querySelector('#safety').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const positive=safetyPositive(questions.map((_,i)=>data.get(`s${i}`)));if(positive||current){modal(`<h2>Are you having thoughts of killing yourself right now?</h2><div class="resource-links">${links}</div><p>If you are in immediate danger, call <a href="tel:911">911</a>. You can contact support without answering.</p><div class="safety-buttons">${['Yes','No','Prefer not to answer'].map(a=>`<button class="secondary" data-answer="${a}">${a}</button>`).join('')}</div>`);dialog.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>result(b.dataset.answer!=='No'||current,true));}else result(false,false);};
 function result(urgent,positive){modal(`<div class="eyebrow">SUPPORT IS AVAILABLE</div><h2>${urgent?'Please connect with live support now.':'A trained person can help you take the next step.'}</h2><p>${urgent?'If you might act on these thoughts, call 988 or JHU crisis support now. In immediate danger call 911 or go to an emergency department. Stay with someone you trust if possible.':positive?'Your responses call for a further safety assessment by a trained clinician. Contact JHU mental health or crisis support promptly.':'These answers cannot establish that you are safe. Because you reported recent concerns, consider contacting a trained professional promptly.'}</p><div class="resource-links">${links}</div><p>No one is monitoring this app. It cannot provide emergency care. Your safety responses have not been saved and do not affect your wellness index.</p><button class="secondary" id="continue-after-safety">Return to reflection</button>`);document.querySelector('#continue-after-safety').onclick=done;}
}
render();
setInterval(()=>{if(!dialog.open&&page==='Overview')render();},60000);
